import type { Lang } from "./translations";

export const AUTHORS_WORLD_COPY: Record<Lang, any> = {
  ua: {
    nav: { back: "← Повернутися до Gathering Of The Fallen", archive: "Інтерактивний архів // точка входу", title: "Сад авторів", intro: "Сад авторів, музики та історій. Знайди голос, який залишився у пам’яті, або залиш тут власний слід.", chat: "Загальний чат", checking: "ПЕРЕВІРКА ДОСТУПУ...", signInPortal: "УВІЙТИ ДЛЯ ПОРТАЛУ", editPortal: "РЕДАГУВАТИ МІЙ ПОРТАЛ", leaveMemory: "ЗАЛИШИТИСЯ У СПОГАДІ" },
    account: { title: "Авторський акаунт", checking: "Перевіряємо email-сесію...", verified: "Email підтверджено", description: "Кожен портал прив’язаний до власного email-акаунта.", loading: "Завантаження...", myPortal: "Мій портал", signOut: "Вийти", signIn: "Увійти email", signUp: "Реєстрація email" },
    world: { title: "Сад авторів", connecting: "підключення до мережі авторів...", portals: "{count} відкритих порталів // наведи курсор, щоб збільшити портал", search: "Пошук", searchPlaceholder: "ім’я або роль", searchAria: "Пошук авторів", found: "GPS // знайдено: {name}", notFound: "GPS // портал не знайдено", searchHint: "Введи ім’я — сад знайде портал", navigationAria: "Поле навігації саду авторів", coordinates: "Координати мережі // перетягни поле для навігації", quiet: "Цей сектор ще мовчить. Спробуй інший запит або залиш власний слід.", closePortal: "Закрити активний портал автора", drag: "Перетягування // нескінченне поле", zoomOut: "Зменшити масштаб поля", zoomIn: "Збільшити масштаб поля", center: "Центрувати мережу авторів" },
    steps: { heading: "Як це працює", items: [["01", "Знайди", "Скануй світ і відкривай нові імена."], ["02", "Зайди", "Натисни на портал і подивись світ автора."], ["03", "Залишся", "Додай власну історію та свої майданчики."]] },
    selected: { open: "Відкритий портал", portrait: "Портрет {name}", openAll: "Відкрити всі роботи автора", choose: "Обери портал у світі, щоб відкрити автора." },
    chat: { eyebrow: "Локальна мережа // світ авторів", title: "Загальний чат", description: "Одна внутрішня кімната для всіх авторів. Повідомлення залишаються на цьому сайті й не передаються у зовнішні месенджери.", connected: "Портал підключений до мережі", required: "Для повідомлень потрібен портал", room: "Головна кімната // усі автори", loading: "Синхронізація історії повідомлень...", empty: "У мережі поки тихо. Відкрий портал і залиш перше повідомлення.", status: "Стан локальної мережі", statusItems: ["Автори бачать імена та ніки одне одного.", "Історія зберігається у спільній кімнаті.", "Канал працює тільки всередині сайту."], inputLabel: "Повідомлення у загальний чат", placeholder: "Написати від імені {name}...", sending: "ВІДПРАВЛЕННЯ...", send: "НАДІСЛАТИ", needsPortal: "Щоб писати у внутрішньому чаті, створи авторський портал після входу на сайт.", signIn: "Увійти", failed: "Повідомлення не відправлено." },
    editor: {
      newPortal: "Новий портал", title: "Залишитися у спогаді", close: "ЗАКРИТИ", closeAria: "Закрити форму", description: "Створи або онови свій портал. Профіль збережеться у внутрішній базі сайту, автоматично з’явиться у світі авторів і дасть доступ до загального чату. Для публікації потрібен акаунт із email та паролем.", signIn: "Увійти", or: "або", createAccount: "створити акаунт",
      name: "Ім’я або псевдонім *", namePlaceholder: "Твоє ім’я або назва проєкту", role: "Хто ти у цьому світі *", rolePlaceholder: "Музикант, авторка, художник...", memory: "Що ти залишаєш у пам’яті? *", memoryPlaceholder: "Коротке послання або опис твоєї творчості",
      avatar: "Іконка профілю", avatarHelp: "Додай свій малюнок. У світі він буде маленьким, а при наведенні повністю розгорнеться разом з інформацією автора.", avatarPreview: "Попередній перегляд аватарки автора", change: "Змінити", preparingAvatar: "ПІДГОТОВКА ІКОНКИ...", avatarReady: "Аватарка готова", pressPlus: "Натисни на плюс", avatarDetails: "Оригінальне зображення збережеться без змін, якщо воно вкладається в ліміт. Великі файли оптимізуються у високій якості. Наведи курсор, щоб побачити його повністю.", directLink: "Або пряме посилання", photoPreview: "Попередній перегляд фото профілю", photoPreviewHelp: "Попередній перегляд. Після збереження фото з’явиться у світі авторів і чаті.",
      background: "Фон профілю", backgroundHelp: "Завантаж широке зображення — воно стане атмосферним тлом твоєї сторінки автора.", preparingBackground: "ПІДГОТОВКА ФОНУ...", addBackground: "ДОДАТИ ФОН ПРОФІЛЮ", backgroundPreviewAria: "Попередній перегляд фону профілю", backgroundPreview: "Попередній перегляд широкого фону",
      platforms: "Твої майданчики", platformsHelp: "Додай окрему адресу для кожного профілю. Порожні рядки не збережуться.", rows: "{count} рядків", platform: "Майданчик {number}", choosePlatform: "Вибрати майданчик {number}", profileAddress: "Адреса профілю", profileAddressAria: "Адреса профілю {number}", removePlatform: "Видалити майданчик {number}", remove: "Видалити", customPlatform: "Назва майданчика", customPlatformPlaceholder: "Наприклад, Telegram або Patreon", noPlatforms: "Поки що немає адрес. Додай перший майданчик нижче.", addPlatform: "Додати майданчик",
      connecting: "ПІДКЛЮЧЕННЯ ДО МЕРЕЖІ...", savePortal: "ЗБЕРЕГТИ МІЙ ПОРТАЛ", openPortal: "ВІДКРИТИ МІЙ ПОРТАЛ",
    },
    creations: { eyebrow: "Публічні роботи", title: "Банери та картки", saved: "{count} збережено", help: "Додай посилання на окрему роботу. Відвідувачі побачать її у вкладці відповідного майданчика, зокрема у вкладці YouTube.", attached: "MP3 прикріплено", edit: "Змінити", remove: "Видалити", platform: "Майданчик", format: "Формат", banner: "Банер", card: "Картка", creation: "Творіння", titleLabel: "Назва роботи *", titlePlaceholder: "Назва пісні, відео або проєкту", description: "Опис", descriptionPlaceholder: "Коротко про цю роботу", uploadMp3: "Завантажити MP3", mp3Help: "Тільки MP3 до 20 МБ. Максимум 5 треків і 100 МБ на один портал.", selected: "ВИБРАНО: {name}", replaceMp3: "MP3 ПРИКРІПЛЕНО — НАТИСНИ, ЩОБ ЗАМІНИТИ", chooseMp3: "ОБРАТИ MP3-ФАЙЛ", contentLink: "Посилання на роботу (необов’язково)", contentPlaceholder: "https://youtube.com/watch?v=... або залиш порожнім для MP3", cover: "Обкладинка (необов’язково)", uploading: "ЗАВАНТАЖЕННЯ MP3...", saving: "ЗБЕРЕЖЕННЯ...", saveChanges: "ЗБЕРЕГТИ ЗМІНИ", addWork: "ДОДАТИ РОБОТУ", cancel: "Скасувати" },
    errors: { avatar: "Не вдалося підготувати іконку.", background: "Не вдалося підготувати фон профілю.", mp3Type: "Потрібен саме MP3-файл.", mp3Size: "MP3 має бути не більшим за 20 МБ.", loadWorld: "Не вдалося завантажити світ авторів.", loadAuthors: "Не вдалося завантажити авторів.", connectChat: "Не вдалося підключитися до загального чату.", chatUnavailable: "Чат тимчасово недоступний.", liveInterrupted: "Live-з’єднання перервано. Спроба відновлення триває.", signInFirst: "Спочатку увійди до акаунта — тоді зміни збережуться у твоєму порталі.", requiredFields: "Заповни, будь ласка, ім’я, роль і коротке послання.", platformAddresses: "Перевір адреси майданчиків.", openPortal: "Не вдалося відкрити портал.", needWork: "Додай MP3-файл або посилання на роботу.", prepareUpload: "Не вдалося підготувати завантаження MP3.", uploadMp3: "MP3 не завантажився у сховище. Спробуй ще раз.", saveWork: "Не вдалося зберегти авторську роботу.", deleteWork: "Не вдалося видалити авторську роботу." },
    notices: { profileSaved: "Збережено. Можеш продовжити редагування нижче.", workSaved: "Збережено. Роботу опубліковано у твоєму порталі." },
    platformLabels: { website: "Сайт / портфоліо", audio: "MP3 / авторська музика", other: "Інший майданчик" },
    header: { checking: "Перевірка доступу...", signIn: "Увійти", myPortal: "Мій портал", signOut: "Вийти", other: "САД", world: "АВТОРІВ", authors: "" },
  },
  en: {
    nav: { back: "← Return to Gathering Of The Fallen", archive: "Interactive archive // entry point", title: "Other World", intro: "A world of authors, music, and stories. Find a voice that remains in memory, or leave your own mark here.", chat: "General chat", checking: "CHECKING ACCESS...", signInPortal: "SIGN IN FOR A PORTAL", editPortal: "EDIT MY PORTAL", leaveMemory: "REMAIN IN MEMORY" },
    account: { title: "Author account", checking: "Checking email session...", verified: "Email verified", description: "Each portal is linked to its own email account.", loading: "Loading...", myPortal: "My portal", signOut: "Sign out", signIn: "Sign in with email", signUp: "Register with email" },
    world: { title: "Authors’ World", connecting: "connecting to the authors’ network...", portals: "{count} open portals // hover to expand a portal", search: "Search", searchPlaceholder: "name or role", searchAria: "Search authors", found: "GPS // found: {name}", notFound: "GPS // portal not found", searchHint: "Enter a name — the world will find the portal", navigationAria: "Authors’ World navigation field", coordinates: "Network coordinates // drag the field to navigate", quiet: "This sector is still silent. Try another query or leave your own mark.", closePortal: "Close active author portal", drag: "Drag // infinite field", zoomOut: "Zoom out", zoomIn: "Zoom in", center: "Center the authors’ network" },
    steps: { heading: "How it works", items: [["01", "Find", "Scan the world and discover new names."], ["02", "Enter", "Select a portal and explore the author’s world."], ["03", "Stay", "Add your own story and platforms."]] },
    selected: { open: "Open portal", portrait: "Portrait of {name}", openAll: "Open all author works", choose: "Choose a portal in the world to open an author." },
    chat: { eyebrow: "Local network // authors’ world", title: "General chat", description: "One private room for all authors. Messages remain on this site and are not sent to external messengers.", connected: "Portal connected to the network", required: "A portal is required to post", room: "Main room // all authors", loading: "Syncing message history...", empty: "The network is quiet. Open a portal and leave the first message.", status: "Local network status", statusItems: ["Authors can see one another’s names and handles.", "History is stored in the shared room.", "The channel works only inside this site."], inputLabel: "Message in general chat", placeholder: "Write as {name}...", sending: "SENDING...", send: "SEND", needsPortal: "To write in the internal chat, create an author portal after signing in.", signIn: "Sign in", failed: "Message could not be sent." },
    editor: {
      newPortal: "New portal", title: "Remain in memory", close: "CLOSE", closeAria: "Close form", description: "Create or update your portal. The profile is stored in the site database, appears automatically in Authors’ World, and unlocks general chat. An email and password account is required to publish.", signIn: "Sign in", or: "or", createAccount: "create an account",
      name: "Name or alias *", namePlaceholder: "Your name or project name", role: "Who are you in this world? *", rolePlaceholder: "Musician, writer, artist...", memory: "What do you leave in memory? *", memoryPlaceholder: "A short message or description of your work",
      avatar: "Profile icon", avatarHelp: "Add your artwork. It appears small in the world and expands with the author information on hover.", avatarPreview: "Author avatar preview", change: "Change", preparingAvatar: "PREPARING ICON...", avatarReady: "Avatar ready", pressPlus: "Press the plus", avatarDetails: "The original image is preserved when it fits the limit. Large files are optimized at high quality. Hover to see it in full.", directLink: "Or a direct link", photoPreview: "Profile photo preview", photoPreviewHelp: "Preview. After saving, the photo appears in Authors’ World and chat.",
      background: "Profile background", backgroundHelp: "Upload a wide image to use as the atmospheric background of your author page.", preparingBackground: "PREPARING BACKGROUND...", addBackground: "ADD PROFILE BACKGROUND", backgroundPreviewAria: "Profile background preview", backgroundPreview: "Wide background preview",
      platforms: "Your platforms", platformsHelp: "Add a separate address for each profile. Empty rows are not saved.", rows: "{count} rows", platform: "Platform {number}", choosePlatform: "Choose platform {number}", profileAddress: "Profile address", profileAddressAria: "Profile address {number}", removePlatform: "Remove platform {number}", remove: "Remove", customPlatform: "Platform name", customPlatformPlaceholder: "For example, Telegram or Patreon", noPlatforms: "No addresses yet. Add the first platform below.", addPlatform: "Add platform",
      connecting: "CONNECTING TO NETWORK...", savePortal: "SAVE MY PORTAL", openPortal: "OPEN MY PORTAL",
    },
    creations: { eyebrow: "Public works", title: "Banners and cards", saved: "{count} saved", help: "Add a link to an individual work. Visitors will see it in the matching platform tab, including YouTube.", attached: "MP3 attached", edit: "Edit", remove: "Remove", platform: "Platform", format: "Format", banner: "Banner", card: "Card", creation: "Creation", titleLabel: "Work title *", titlePlaceholder: "Song, video, or project title", description: "Description", descriptionPlaceholder: "A short description of this work", uploadMp3: "Upload MP3", mp3Help: "MP3 only, up to 20 MB. Maximum 5 tracks and 100 MB per portal.", selected: "SELECTED: {name}", replaceMp3: "MP3 ATTACHED — PRESS TO REPLACE", chooseMp3: "CHOOSE MP3 FILE", contentLink: "Work link (optional)", contentPlaceholder: "https://youtube.com/watch?v=... or leave empty for MP3", cover: "Cover (optional)", uploading: "UPLOADING MP3...", saving: "SAVING...", saveChanges: "SAVE CHANGES", addWork: "ADD WORK", cancel: "Cancel" },
    errors: { avatar: "The profile icon could not be prepared.", background: "The profile background could not be prepared.", mp3Type: "Please choose an MP3 file.", mp3Size: "The MP3 must be no larger than 20 MB.", loadWorld: "Authors’ World could not be loaded.", loadAuthors: "The authors could not be loaded.", connectChat: "Could not connect to general chat.", chatUnavailable: "Chat is temporarily unavailable.", liveInterrupted: "The live connection was interrupted. Reconnecting now.", signInFirst: "Sign in first so your changes can be saved to your portal.", requiredFields: "Please enter a name, role, and short message.", platformAddresses: "Check the platform addresses.", openPortal: "The portal could not be opened.", needWork: "Add an MP3 file or a link to the work.", prepareUpload: "The MP3 upload could not be prepared.", uploadMp3: "The MP3 did not upload to storage. Please try again.", saveWork: "The author work could not be saved.", deleteWork: "The author work could not be removed." },
    notices: { profileSaved: "Saved. You can continue editing below.", workSaved: "Saved. The work is now published in your portal." },
    platformLabels: { website: "Website / portfolio", audio: "MP3 / original music", other: "Other platform" },
    header: { checking: "Checking access...", signIn: "Sign in", myPortal: "My portal", signOut: "Sign out", other: "OTHER", world: "WORLD", authors: "AUTHORS" },
  },
  fr: {
    nav: { back: "← Retour à Gathering Of The Fallen", archive: "Archives interactives // point d’entrée", title: "Autre Monde", intro: "Un monde d’auteurs, de musique et d’histoires. Trouvez une voix qui demeure dans la mémoire, ou laissez votre propre trace.", chat: "Discussion générale", checking: "VÉRIFICATION DE L’ACCÈS...", signInPortal: "SE CONNECTER POUR UN PORTAIL", editPortal: "MODIFIER MON PORTAIL", leaveMemory: "RESTER DANS LA MÉMOIRE" },
    account: { title: "Compte d’auteur", checking: "Vérification de la session e-mail...", verified: "E-mail vérifié", description: "Chaque portail est lié à son propre compte e-mail.", loading: "Chargement...", myPortal: "Mon portail", signOut: "Déconnexion", signIn: "Connexion par e-mail", signUp: "Inscription par e-mail" },
    world: { title: "Monde des auteurs", connecting: "connexion au réseau des auteurs...", portals: "{count} portails ouverts // survolez pour agrandir", search: "Recherche", searchPlaceholder: "nom ou rôle", searchAria: "Rechercher des auteurs", found: "GPS // trouvé : {name}", notFound: "GPS // portail introuvable", searchHint: "Saisissez un nom — le monde trouvera le portail", navigationAria: "Zone de navigation du Monde des auteurs", coordinates: "Coordonnées du réseau // faites glisser pour naviguer", quiet: "Ce secteur est encore silencieux. Essayez une autre recherche ou laissez votre trace.", closePortal: "Fermer le portail actif", drag: "Glisser // espace infini", zoomOut: "Réduire le zoom", zoomIn: "Agrandir le zoom", center: "Centrer le réseau des auteurs" },
    steps: { heading: "Comment ça marche", items: [["01", "Trouvez", "Explorez le monde et découvrez de nouveaux noms."], ["02", "Entrez", "Choisissez un portail et découvrez le monde de l’auteur."], ["03", "Restez", "Ajoutez votre histoire et vos plateformes."]] },
    selected: { open: "Portail ouvert", portrait: "Portrait de {name}", openAll: "Voir toutes les œuvres de l’auteur", choose: "Choisissez un portail pour ouvrir un auteur." },
    chat: { eyebrow: "Réseau local // monde des auteurs", title: "Discussion générale", description: "Une salle privée pour tous les auteurs. Les messages restent sur ce site et ne sont pas transmis à des messageries externes.", connected: "Portail connecté au réseau", required: "Un portail est requis pour publier", room: "Salle principale // tous les auteurs", loading: "Synchronisation de l’historique...", empty: "Le réseau est silencieux. Ouvrez un portail et laissez le premier message.", status: "État du réseau local", statusItems: ["Les auteurs voient les noms et identifiants des autres.", "L’historique est conservé dans la salle commune.", "Le canal fonctionne uniquement sur ce site."], inputLabel: "Message dans la discussion générale", placeholder: "Écrire en tant que {name}...", sending: "ENVOI...", send: "ENVOYER", needsPortal: "Pour écrire dans la discussion interne, créez un portail d’auteur après vous être connecté.", signIn: "Se connecter", failed: "Le message n’a pas pu être envoyé." },
    editor: {
      newPortal: "Nouveau portail", title: "Rester dans la mémoire", close: "FERMER", closeAria: "Fermer le formulaire", description: "Créez ou mettez à jour votre portail. Le profil est conservé dans la base du site, apparaît automatiquement dans le Monde des auteurs et donne accès à la discussion générale. Un compte e-mail avec mot de passe est requis.", signIn: "Se connecter", or: "ou", createAccount: "créer un compte",
      name: "Nom ou pseudonyme *", namePlaceholder: "Votre nom ou celui du projet", role: "Qui êtes-vous dans ce monde ? *", rolePlaceholder: "Musicien, auteur, artiste...", memory: "Que laissez-vous dans la mémoire ? *", memoryPlaceholder: "Un court message ou une description de votre travail",
      avatar: "Icône du profil", avatarHelp: "Ajoutez votre image. Elle apparaît en petit dans le monde et s’agrandit avec les informations de l’auteur au survol.", avatarPreview: "Aperçu de l’avatar", change: "Modifier", preparingAvatar: "PRÉPARATION DE L’ICÔNE...", avatarReady: "Avatar prêt", pressPlus: "Appuyez sur le plus", avatarDetails: "L’image originale est conservée si elle respecte la limite. Les grands fichiers sont optimisés en haute qualité. Survolez pour la voir entièrement.", directLink: "Ou un lien direct", photoPreview: "Aperçu de la photo du profil", photoPreviewHelp: "Aperçu. Après l’enregistrement, la photo apparaîtra dans le Monde des auteurs et le chat.",
      background: "Fond du profil", backgroundHelp: "Téléversez une image large pour créer le fond atmosphérique de votre page d’auteur.", preparingBackground: "PRÉPARATION DU FOND...", addBackground: "AJOUTER UN FOND DE PROFIL", backgroundPreviewAria: "Aperçu du fond du profil", backgroundPreview: "Aperçu du fond large",
      platforms: "Vos plateformes", platformsHelp: "Ajoutez une adresse distincte pour chaque profil. Les lignes vides ne seront pas enregistrées.", rows: "{count} lignes", platform: "Plateforme {number}", choosePlatform: "Choisir la plateforme {number}", profileAddress: "Adresse du profil", profileAddressAria: "Adresse du profil {number}", removePlatform: "Supprimer la plateforme {number}", remove: "Supprimer", customPlatform: "Nom de la plateforme", customPlatformPlaceholder: "Par exemple, Telegram ou Patreon", noPlatforms: "Aucune adresse. Ajoutez la première plateforme ci-dessous.", addPlatform: "Ajouter une plateforme",
      connecting: "CONNEXION AU RÉSEAU...", savePortal: "ENREGISTRER MON PORTAIL", openPortal: "OUVRIR MON PORTAIL",
    },
    creations: { eyebrow: "Œuvres publiques", title: "Bannières et cartes", saved: "{count} enregistrées", help: "Ajoutez un lien vers une œuvre. Les visiteurs la verront dans l’onglet de la plateforme correspondante, notamment YouTube.", attached: "MP3 joint", edit: "Modifier", remove: "Supprimer", platform: "Plateforme", format: "Format", banner: "Bannière", card: "Carte", creation: "Création", titleLabel: "Titre de l’œuvre *", titlePlaceholder: "Titre de la chanson, vidéo ou du projet", description: "Description", descriptionPlaceholder: "Une courte description de cette œuvre", uploadMp3: "Téléverser un MP3", mp3Help: "MP3 uniquement, jusqu’à 20 Mo. Maximum 5 titres et 100 Mo par portail.", selected: "SÉLECTIONNÉ : {name}", replaceMp3: "MP3 JOINT — APPUYEZ POUR REMPLACER", chooseMp3: "CHOISIR UN FICHIER MP3", contentLink: "Lien vers l’œuvre (facultatif)", contentPlaceholder: "https://youtube.com/watch?v=... ou laissez vide pour le MP3", cover: "Pochette (facultatif)", uploading: "TÉLÉVERSEMENT DU MP3...", saving: "ENREGISTREMENT...", saveChanges: "ENREGISTRER LES MODIFICATIONS", addWork: "AJOUTER UNE ŒUVRE", cancel: "Annuler" },
    errors: { avatar: "Impossible de préparer l’icône du profil.", background: "Impossible de préparer le fond du profil.", mp3Type: "Veuillez choisir un fichier MP3.", mp3Size: "Le MP3 ne doit pas dépasser 20 Mo.", loadWorld: "Impossible de charger le Monde des auteurs.", loadAuthors: "Impossible de charger les auteurs.", connectChat: "Impossible de se connecter à la discussion générale.", chatUnavailable: "La discussion est temporairement indisponible.", liveInterrupted: "La connexion en direct a été interrompue. Reconnexion en cours.", signInFirst: "Connectez-vous d’abord pour enregistrer les modifications dans votre portail.", requiredFields: "Veuillez saisir un nom, un rôle et un court message.", platformAddresses: "Vérifiez les adresses des plateformes.", openPortal: "Impossible d’ouvrir le portail.", needWork: "Ajoutez un fichier MP3 ou un lien vers l’œuvre.", prepareUpload: "Impossible de préparer le téléversement du MP3.", uploadMp3: "Le MP3 n’a pas été téléversé. Veuillez réessayer.", saveWork: "Impossible d’enregistrer l’œuvre.", deleteWork: "Impossible de supprimer l’œuvre." },
    notices: { profileSaved: "Enregistré. Vous pouvez continuer la modification ci-dessous.", workSaved: "Enregistré. L’œuvre est publiée dans votre portail." },
    platformLabels: { website: "Site / portfolio", audio: "MP3 / musique originale", other: "Autre plateforme" },
    header: { checking: "Vérification...", signIn: "Connexion", myPortal: "Mon portail", signOut: "Déconnexion", other: "AUTRE", world: "MONDE", authors: "AUTEURS" },
  },
};

export function formatAuthorsWorldCopy(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""));
}